# Generated by Django 4.0.3 on 2022-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='starting_time',
        ),
        migrations.AlterField(
            model_name='events',
            name='duration',
            field=models.IntegerField(db_index=True, default=0, help_text='The duration of the event in minutes'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
