# Generated by Django 4.0.3 on 2022-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_starting_time_alter_events_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='starting_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
